import type { Service } from "@/types/booking";

const now = () => new Date().toISOString();

export const placeholderServices: Service[] = [
  // Massages
  {
    id: "svc-massage-relaxant-60",
    name: "Massage Relaxant",
    description: null,
    duration_minutes: 60,
    price: 400,
    category: "Massages",
    active: true,
    image_url: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-massage-relaxant-30",
    name: "Massage Relaxant",
    description: null,
    duration_minutes: 30,
    price: 300,
    category: "Massages",
    active: true,
    image_url: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-massage-tonique-60",
    name: "Massage Tonique",
    description: null,
    duration_minutes: 60,
    price: 500,
    category: "Massages",
    active: true,
    image_url: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-massage-tonique-30",
    name: "Massage Tonique",
    description: null,
    duration_minutes: 30,
    price: 400,
    category: "Massages",
    active: true,
    image_url: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-foot-massage-60",
    name: "Foot Massage",
    description: null,
    duration_minutes: 60,
    price: 500,
    category: "Massages",
    active: true,
    image_url: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-foot-massage-30",
    name: "Foot Massage",
    description: null,
    duration_minutes: 30,
    price: 400,
    category: "Massages",
    active: true,
    image_url: null,
    created_at: now(),
    updated_at: now(),
  },
  // Hammams
  {
    id: "svc-hammam-traditionnel-60",
    name: "Hammam Traditionnel",
    description: "Inclut: Hammam Gommage Au Savon Noir + Savonage",
    duration_minutes: 60,
    price: 400,
    category: "Hammams",
    active: true,
    image_url: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-hammam-traditionnel-30",
    name: "Hammam Traditionnel",
    description: "Inclut: Hammam Gommage Au Savon Noir + Savonage",
    duration_minutes: 30,
    price: 300,
    category: "Hammams",
    active: true,
    image_url: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-hammam-royal-60",
    name: "Hammam Royal",
    description: "Inclut: Hammam Gommage Au Savon Noir + Savonage",
    duration_minutes: 60,
    price: 500,
    category: "Hammams",
    active: true,
    image_url: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-hammam-royal-30",
    name: "Hammam Royal",
    description: "Inclut: Hammam Gommage Au Savon Noir + Savonage",
    duration_minutes: 30,
    price: 400,
    category: "Hammams",
    active: true,
    image_url: null,
    created_at: now(),
    updated_at: now(),
  },
  // Packs
  {
    id: "svc-pack-prince",
    name: "Prince",
    description: "Inclut: Hammam Traditionnel + Massage Relaxant",
    duration_minutes: 45,
    price: 500,
    category: "Packs",
    active: true,
    image_url: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-pack-royal",
    name: "Royal",
    description: "Inclut: Hammam Royal + Massage Relaxant",
    duration_minutes: 45,
    price: 600,
    category: "Packs",
    active: true,
    image_url: null,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: "svc-pack-parfait",
    name: "Parfait",
    description: "Inclut: Hammam Royal + Massage Tonique",
    duration_minutes: 60,
    price: 700,
    category: "Packs",
    active: true,
    image_url: null,
    created_at: now(),
    updated_at: now(),
  },
];