import type { Service } from "@/types/booking";

export const placeholderServices: Service[] = [
  // Hair
  {
    id: "placeholder-hair-1",
    name: "Precision Cut",
    description: "A tailored haircut designed to complement your face shape and hair type.",
    duration_minutes: 45,
    price: 55,
    category: "Hair",
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "placeholder-hair-2",
    name: "Color & Highlights",
    description: "Full-color application with hand-painted highlights for a natural look.",
    duration_minutes: 120,
    price: 120,
    category: "Hair",
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "placeholder-hair-3",
    name: "Blowout & Styling",
    description: "Professional blow-dry and styling for any occasion.",
    duration_minutes: 45,
    price: 45,
    category: "Hair",
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "placeholder-hair-4",
    name: "Deep Conditioning Treatment",
    description: "Intensive moisture treatment to restore shine and health to your hair.",
    duration_minutes: 30,
    price: 35,
    category: "Hair",
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Nails
  {
    id: "placeholder-nail-1",
    name: "Classic Manicure",
    description: "Nail shaping, cuticle care, and polish application for perfectly groomed hands.",
    duration_minutes: 30,
    price: 35,
    category: "Nails",
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "placeholder-nail-2",
    name: "Gel Extensions",
    description: "Long-lasting gel overlay with optional length extension.",
    duration_minutes: 75,
    price: 65,
    category: "Nails",
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "placeholder-nail-3",
    name: "Nail Art Design",
    description: "Custom hand-painted nail art with premium materials.",
    duration_minutes: 60,
    price: 50,
    category: "Nails",
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "placeholder-nail-4",
    name: "Spa Pedicure",
    description: "Luxurious foot soak, exfoliation, and polish for rejuvenated feet.",
    duration_minutes: 45,
    price: 55,
    category: "Nails",
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Facials
  {
    id: "placeholder-facial-1",
    name: "Classic Facial",
    description: "Deep cleanse, exfoliation, mask, and moisturizer for radiant skin.",
    duration_minutes: 60,
    price: 85,
    category: "Facials",
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "placeholder-facial-2",
    name: "Anti-Aging Facial",
    description: "Targeted treatment with collagen-boosting serums and microcurrent.",
    duration_minutes: 75,
    price: 110,
    category: "Facials",
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "placeholder-facial-3",
    name: "HydraFacial",
    description: "Advanced hydration treatment that cleanses, peels, and infuses nutrients.",
    duration_minutes: 45,
    price: 95,
    category: "Facials",
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "placeholder-facial-4",
    name: "Chemical Peel",
    description: "Medical-grade peel to improve texture, tone, and clarity.",
    duration_minutes: 45,
    price: 130,
    category: "Facials",
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Makeup
  {
    id: "placeholder-makeup-1",
    name: "Bridal Makeup",
    description: "Full-face bridal makeup with long-wear products and trial included.",
    duration_minutes: 90,
    price: 150,
    category: "Makeup",
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "placeholder-makeup-2",
    name: "Everyday Glam",
    description: "Natural, polished makeup perfect for photos or a night out.",
    duration_minutes: 45,
    price: 65,
    category: "Makeup",
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "placeholder-makeup-3",
    name: "Lash Extensions",
    description: "Semi-permanent lashes for a fuller, longer look without mascara.",
    duration_minutes: 60,
    price: 80,
    category: "Makeup",
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "placeholder-makeup-4",
    name: "Brow Shaping & Tint",
    description: "Expert brow shaping with semi-permanent tint for defined brows.",
    duration_minutes: 30,
    price: 40,
    category: "Makeup",
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
